### ISSUE TITLE
Design and Implement VLA API

### ISSUE THREAD

**Issue by caseyjlaw** [realfastvla/realfast#26]
The integration of realfast with the VLA observing system should be a prototype of a general system for third-party systems. As such, a general interface needs to be designed for systems like this.

**Comment by caseyjlaw** [comment]
Idea came up in a telecon to consider that the realfast system could *itself* have an API. This would allow tighter integration (faster data rates, maybe?) between CBE and realfast. Then the head node may schedule any kind of work on the cluster.
Could be super effective way to define an API, since computing and scheduler are flexible (and written in Python!).

**Comment by bryanbutler2** [comment]
yeah, i hadn't thought of it this way before and it provides a lot of 
flexibility.  i'm not quite ready to embrace it fully because i haven't 
thought enough about it, but it's definitely attractive...

	-bryan


Casey Law wrote on 9/21/16 16:05 :

**Comment by caseyjlaw** [comment]
Martin's vys protocol naturally allows 3rd parties to connect to correlator without impacting primary operations on the CBE. There is a Python API and some applications being collected at http://github.com/realfastvla/vysmaw_apps
