### ISSUE TITLE
Set up realfast user for group access to software

### ISSUE THREAD

**Issue by caseyjlaw** [realfastvla/realfast#32]
Currently the realfast system runs by setting the realfast@cbe-node-01 path to include @caseyjlaw software. Bad!

A group-controlled realfast user needs to be defined.

**Comment by demorest** [comment]
NRAO computing set up the group permissions for realfast a few weeks ago, using the existing 'fasttransients' group.  I didn't yet change any of the file permissions under the realfast area, or anything since I thought it would be better to wait until the current observing campaign is done.

**Comment by caseyjlaw** [comment]
Agreed! Fortunately we finish observing soon. I'm hoping to reorganize before the NRAO internal review in ~a month or so.

**Comment by caseyjlaw** [comment]
This is now working. Members of the 'fasttransients' group can see the cbe home directory at:
`/home/widar-boot-1/services/diskless_boot/cbe/cbe-master/realfast`.

To install software for realfast@cbe, you need to use conda or pip (from AOC) with this in your path:
`/home/widar-boot-1/services/diskless_boot/cbe/cbe-master/realfast/miniconda/bin`

With that set, you can do `conda install numpy` or `pip install rtpipe` and it will install on for realfast@cbe. We can also now play with conda environments to allow testing simultaneously with code that is running live.
